---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/companies":
    post:
      summary: Creates a company
      tags:
      - Companies
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: company created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: object
                  properties:
                    legal_name:
                      type: string
                    company_type:
                      type: string
                    phone_number:
                      type: string
                    registration_number:
                      type: string
                    vat_id:
                      type: string
  "/api/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - username
                  - email
                  - password
                  - password_confirmation
              required:
              - user
  "/api/users/login":
    post:
      summary: Logs in a user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user logged in
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
